---

- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Download vip rbac manifest to first master
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: /var/lib/rancher/k3s/server/manifests/vip-rbac.yaml
    owner: root
    group: root
    mode: "0644"

- name: Copy vip manifest to first master
  ansible.builtin.template:
    src: vip-access.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/vip-access.yaml
    owner: root
    group: root
    mode: "0644"
- name: Copy vip manifest to first master
  ansible.builtin.template:
    src: vip-cluster.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/vip-cluster.yaml
    owner: root
    group: root
    mode: "0644"